-- Complete seed_exercises.sql - 80+ exercises across all categories
-- Run this after creating tables in Supabase

INSERT INTO exercises (name, category, estimated_calories, benefits, steps, instructions, reps, difficulty) VALUES
-- CARDIO (20+)
('Jumping Jacks', 'cardio', 15, 'A full-body movement that quickly raises your heart rate.', ARRAY['Stand feet together arms at sides', 'Jump spreading legs raising arms overhead', 'Return to start', 'Repeat rhythmically'], 'Keep core engaged land softly.', '3 sets of 30 reps', 'Beginner'),
('Running', 'cardio', 300, 'A fast-paced activity that improves cardiovascular endurance.', ARRAY['Warm up walk', 'Maintain steady pace', 'Cool down stretch'], 'Good posture breathing rhythm.', '20-40 minutes', 'Intermediate'),
('Jogging', 'cardio', 250, 'A slower form of running that builds stamina over time.', ARRAY['Start slow comfortable pace', 'Gradual intervals', 'Cool down walk'], 'Easy pace conversation possible.', '30 minutes', 'Beginner'),
('Cycling', 'cardio', 200, 'A low-impact exercise that strengthens legs and improves heart health.', ARRAY['Adjust bike fit', 'Warm up easy pedaling', 'Build intensity', 'Cool down'], 'Maintain cadence 80-100 rpm.', '30-45 minutes', 'Intermediate'),
('Jump Rope', 'cardio', 18, 'A rhythmic activity that boosts coordination and burns calories.', ARRAY['Basic bounce', 'Alternate foot jumps', 'Crossovers', 'High knees'], 'Light rope wrists rotate.', '10 minutes', 'Beginner'),
('Burpees', 'cardio', 20, 'High-intensity exercise combining jumping squatting push-ups.', ARRAY['Squat jump back plank', 'Push-up jump forward', 'Explode up clap'], 'Scale by stepping jumping.', '3 sets of 10', 'Advanced'),
('High Knees', 'cardio', 16, 'Running in place lifting knees high to increase heart rate.', ARRAY['Run place drive knees', 'Pump arms fast', 'Stay light feet'], 'Quick feet tall posture.', '3 sets 30s', 'Beginner'),
('Mountain Climbers', 'cardio', 14, 'Fast core cardio workout mimics climbing motion.', ARRAY['Plank position', 'Drive knee to chest alternate', 'High speed low hips'], 'Core tight quick feet.', '3 sets 30s', 'Intermediate'),
('Stair Climbing', 'cardio', 220, 'Repeatedly going up stairs builds endurance leg strength.', ARRAY['Walk up stairs', 'Jog down recover', 'Repeat intervals'], 'Handrail safety pump arms.', '15 minutes', 'Intermediate'),
('Dancing', 'cardio', 180, 'Fun activity improves cardiovascular fitness coordination.', ARRAY['Warm up grooves', 'Full dance routine', 'Cool down stretch'], 'Follow beat smile enjoy.', '30 minutes', 'Beginner'),
('Skaters', 'cardio', 17, 'Side-to-side jumping enhances agility burns calories.', ARRAY['Lateral jumps', 'Single leg landings', 'Speed up'], 'Athletic stance quick feet.', '3 sets 20 jumps', 'Intermediate'),
('Sprinting', 'cardio', 350, 'Short bursts fast running improve speed power.', ARRAY['Warm up dynamic stretch', 'Sprint intervals', 'Walk recover', 'Cool down'], 'Full effort max speed.', '6-8 x 30s', 'Advanced'),
('Rowing', 'cardio', 210, 'Full-body exercise works upper lower muscles.', ARRAY['Legs drive', 'Body swing', 'Arms pull'], 'Ratio 1:2 recovery.', '20 minutes', 'Intermediate'),
('Swimming', 'cardio', 190, 'Total-body workout gentle on joints.', ARRAY['Warm up easy swim', 'Intervals strokes', 'Cool down backstroke'], 'Breathe rhythm form first.', '30 minutes', 'Intermediate'),
('Kickboxing', 'cardio', 230, 'High-energy workout punches kicks.', ARRAY['Jab cross hook', 'Front side kicks', 'Knee elbows', 'Shadow box combos'], 'Gloves hand wraps technique.', '45 minutes', 'Intermediate'),
('Hiking', 'cardio', 170, 'Walking trails improves endurance leg strength.', ARRAY['Pace yourself terrain', 'Hydrate snacks', 'Watch footing'], 'Good shoes trekking poles.', '2 hours', 'Beginner'),
('Elliptical Training', 'cardio', 200, 'Low-impact cardio machine full-body conditioning.', ARRAY['Warm up low resistance', 'Intervals incline', 'Cool down'], 'Arms legs sync upright.', '30 minutes', 'Beginner'),
('Fast Walking', 'cardio', 150, 'Brisk walk improves heart health stamina.', ARRAY['Power walk arms pump', 'Good posture', 'Incline optional'], 'Purposeful stride swing arms.', '45 minutes', 'Beginner'),
('Zumba', 'cardio', 185, 'Dance-based workout combines fun cardio.', ARRAY['Latin rhythms choreography', 'High low impact', 'Party atmosphere'], 'Follow instructor mirror.', '60 minutes', 'Beginner'),
('Shadow Boxing', 'cardio', 160, 'Punching movements air build speed endurance.', ARRAY['Stance footwork', 'Jabs crosses hooks', 'Uppercuts ducks slips', 'Combinations'], 'Light feet bounce shadow mirror.', '20 minutes', 'Beginner'),

-- STRENGTH (20+)
('Push-ups', 'strength', 10, 'Builds strength chest shoulders arms.', ARRAY['Plank hands shoulder width', 'Lower chest elbows 45°', 'Push up straight line'], 'Knees beginners full later.', '3 sets 12-15', 'Intermediate'),
('Squats', 'strength', 12, 'Strengthens legs glutes repeated bending.', ARRAY['Feet shoulder width toes out', 'Sit back chest up', 'Knees track toes', 'Drive heels explode up'], 'Depth ability core tight.', '3 sets 15', 'Beginner'),
('Plank', 'strength', 5, 'Static hold strengthens core muscles.', ARRAY['Forearms shoulders aligned', 'Body straight heels hips', 'Core glutes tight'], 'No sagging piking breathe.', '3 sets 45-60s', 'Intermediate'),
('Lunges', 'strength', 9, 'Stepping movement targets legs improves balance.', ARRAY['Step forward torso upright', 'Both knees 90°', 'Push front heel start', 'Alternate legs'], 'Front knee tracks toe.', '3 sets 10/leg', 'Beginner'),
('Bicep Curls', 'strength', 6, 'Lifts weights strengthen front arm muscles.', ARRAY['Palms forward shoulder width', 'Curl squeeze biceps', 'Slow negative elbows fixed'], 'No swinging full range.', '3 sets 12', 'Beginner'),
('Tricep Dips', 'strength', 9, 'Body weight strengthens back arms.', ARRAY['Bench edge hands beside hips', 'Slide butt knees 90°', 'Lower elbows 90°', 'Press up triceps'], 'Shoulders down elbows back.', '3 sets 12', 'Intermediate'),
('Wall Sit', 'strength', 7, 'Seated position wall builds leg endurance.', ARRAY['Back wall thighs parallel', 'Knees 90° weight heels', 'Arms chest hold'], 'Core tight breathe steady.', '3 sets 45s', 'Intermediate'),
('Glute Bridge', 'strength', 8, 'Lifts hips strengthens glutes lower back.', ARRAY['Supine knees bent feet flat', 'Lift hips squeeze glutes', 'Top hold lower control'], 'No arch lower back.', '3 sets 15', 'Beginner'),
('Deadlifts', 'strength', 15, 'Lifting weights ground build full-body strength.', ARRAY['Feet hip width bar shins', 'Hinge grip shoulders back', 'Drive heels hips forward', 'Lock out squeeze'], 'Neutral spine brace core.', '3 sets 8', 'Advanced'),
('Shoulder Press', 'strength', 11, 'Pushing weights upward strengthens shoulders.', ARRAY['Dumbbells shoulders palms forward', 'Press overhead lockout', 'Lower control shoulders down'], 'Core tight no arch.', '3 sets 10', 'Intermediate'),
('Pull-ups', 'strength', 13, 'Lifting body bar strengthens upper body.', ARRAY['Overhand grip shoulder width', 'Pull chin bar', 'Slow negative control'], 'Assisted bands beginners.', '3 sets 6-8', 'Advanced'),
('Leg Press', 'strength', 18, 'Pushing weight legs build lower-body strength.', ARRAY['Feet mid platform shoulder width', 'Lower control knees 90°', 'Explode up don''t lock'], 'Full range back flat.', '3 sets 12', 'Intermediate'),
('Calf Raises', 'strength', 5, 'Lifting heels strengthens lower legs.', ARRAY['Shoulder width full range', 'Pause top squeeze', 'Slow lower stretch'], 'Straight knees bodyweight first.', '3 sets 20', 'Beginner'),
('Bench Press', 'strength', 14, 'Pressing weights lying down build chest muscles.', ARRAY['Retracted scapula bar chest', 'Lower elbows 45°', 'Drive up triple extension'], 'Arch safety bars.', '3 sets 8-10', 'Intermediate'),
('Russian Twists', 'strength', 7, 'Rotating torso strengthens core.', ARRAY['Sit knees bent lean back', 'Rotate touch ground each side', 'Controlled speed'], 'No jerking feet down advanced.', '3 sets 20/side', 'Intermediate'),
('Step-ups', 'strength', 10, 'Stepping platform builds leg strength.', ARRAY['Knee height step', 'Drive heel up', 'Step down control'], 'Alternate leading knee high.', '3 sets 12/leg', 'Beginner'),
('Chest Fly', 'strength', 9, 'Opening closing arms weights target chest.', ARRAY['Flat bench slight bend elbows', 'Arc hug motion', 'Stretch bottom squeeze top'], 'No shoulder strain.', '3 sets 12', 'Intermediate'),
('Lat Pulldown', 'strength', 12, 'Pulling bar down strengthens back muscles.', ARRAY['Wide grip chest up', 'Pull elbows back squeeze', 'Slow release full stretch'], 'Lean back slight no jerk.', '3 sets 10', 'Intermediate'),
('Hammer Curls', 'strength', 6, 'Lifting weights neutral grip strengthen arms.', ARRAY['Thumbs up hammer position', 'Curl simultaneous alternate', 'Full range squeeze'], 'Elbows fixed torso stable.', '3 sets 12', 'Beginner'),
('Leg Raises', 'strength', 8, 'Lifting legs strengthens abdominal muscles.', ARRAY['Hanging bar or captain chair', 'Controlled lift knees chest', 'Slow lower no swing'], 'No momentum engage abs.', '3 sets 12', 'Intermediate'),

-- FLEXIBILITY (20+)
('Hamstring Stretch', 'flexibility', 2, 'Extends back legs improve flexibility.', ARRAY['Seated one leg extended', 'Reach forward spine straight', 'Flex foot hold'], 'No bounce breathe relax.', '30s each side', 'Beginner'),
('Shoulder Stretch', 'flexibility', 1, 'Loosens shoulder muscles range motion.', ARRAY['Arm across chest', 'Opposite hand pulls elbow', 'Keep shoulders down'], 'Gentle no pain.', '30s each arm', 'Beginner'),
('Cobra Stretch', 'flexibility', 2, 'Bends back stretch abdomen spine.', ARRAY['Prone palms under shoulders', 'Lift chest elbows soft', 'Head neutral gaze forward'], 'Shoulders from ears.', '30s hold', 'Beginner'),
('Butterfly Stretch', 'flexibility', 2, 'Opens hips stretches inner thighs.', ARRAY['Soles together knees out', 'Gentle forward fold', 'Hands on feet back straight'], 'Flap knees relax.', '1 minute', 'Beginner'),
('Side Stretch', 'flexibility', 2, 'Reaches sideways stretch torso.', ARRAY['Seated standing one arm overhead', 'Bend sideways away', 'Hand supports'], 'Hips grounded no lean forward.', '30s each side', 'Beginner'),
('Quadriceps Stretch', 'flexibility', 1, 'Pulls foot body stretch front thigh.', ARRAY['Standing hand behind wall', 'Heel to glutes knee pointing down', 'Push hips forward'], 'Knees together quad focus.', '30s each leg', 'Beginner'),
('Neck Stretch', 'flexibility', 1, 'Gently tilts head relieve neck tension.', ARRAY['Ear shoulder gentle hand assist', 'Hold breathe', 'All 4 directions'], 'No forcing pain free.', '20s each side', 'Beginner'),
('Cat-Cow Stretch', 'flexibility', 3, 'Alternates spine positions improve flexibility.', ARRAY['Tabletop hands knees', 'Cat arch round exhale', 'Cow dip belly inhale'], 'Flow breath 5-10 cycles.', '1 minute', 'Beginner'),
('Standing Toe Touch', 'flexibility', 2, 'Reaches toes stretch hamstrings back.', ARRAY['Feet hip width knees soft', 'Hinge hips forward', 'Hands shins floor'], 'Spine long no round.', '30s hold', 'Beginner'),
('Hip Flexor Stretch', 'flexibility', 2, 'Opens hips stretches upper thighs.', ARRAY['Lunge back knee down', 'Front leg 90° hips square', 'Tuck pelvis forward'], 'Back straight tall.', '30s each side', 'Intermediate'),
('Child''s Pose', 'flexibility', 1, 'Resting stretch relaxes back shoulders.', ARRAY['Knees wide big toes touch', 'Walk hands forward', 'Forehead to floor arms extended'], 'Breathe hips to heels.', '1 minute', 'Beginner'),
('Seated Forward Bend', 'flexibility', 2, 'Reaches forward seated stretch spine.', ARRAY['Legs extended', 'Hinge hips forward', 'Reach past feet'], 'Bend knees if tight.', '1 minute', 'Beginner'),
('Triceps Stretch', 'flexibility', 1, 'Bends arm overhead stretch upper arm.', ARRAY['One arm overhead elbow bent', 'Other hand above elbow', 'Gentle pull'], 'Shoulder down no strain.', '30s each arm', 'Beginner'),
('Spinal Twist', 'flexibility', 2, 'Rotates body stretch spine.', ARRAY['Seated cross leg', 'Hand opposite knee', 'Twist look back'], 'Lengthen first then twist.', '30s each side', 'Beginner'),
('Figure Four Stretch', 'flexibility', '3', 'Opens hips stretches glutes.', ARRAY['Supine ankle over opposite knee', 'Pull thigh toward chest', 'Keep head down'], 'Flex top foot.', '30s each side', 'Intermediate'),
('Groin Stretch', 'flexibility', 1, 'Stretches inner thigh muscles.', ARRAY['Wide legs sit', 'Lean forward between legs', 'Back straight'], 'Symmetric no force.', '1 minute', 'Beginner'),
('Calf Stretch', 'flexibility', 1, 'Extends lower leg muscles.', ARRAY['Wall one foot back', 'Front knee bent back straight', 'Heel ground'], 'Switch legs hold.', '30s each', 'Beginner'),
('Wrist Stretch', 'flexibility', 1, 'Improves flexibility wrists forearms.', ARRAY['Extend arm palm up', 'Pull fingers back with other hand', 'Then palm down pull back'], 'Gentle no pain.', '20s each direction', 'Beginner'),
('Backbend Stretch', 'flexibility', 3, 'Arches back improve spinal flexibility.', ARRAY['Bridge pose or wheel', 'Hands feet shoulders hips lift', 'Look up shoulders back'], 'Modify bridge beginners.', '5 breaths', 'Intermediate'),
('Overhead Stretch', 'flexibility', 1, 'Reaches arms upward stretch upper body.', ARRAY['Interlace fingers palms up', 'Reach overhead side bend', 'Exhale center'], 'Shoulders relaxed.', '30s each side', 'Beginner'),

-- BALANCE (20+)
('Single-Leg Stand', 'balance', 2, 'Standing one leg improve stability.', ARRAY['Barefoot gaze fixed point', 'Knee soft arms out', 'Build time'], 'Quiet mind focus.', '30s-1min each', 'Beginner'),
('Heel-to-Toe Walk', 'balance', 3, 'Walking straight line enhance coordination.', ARRAY['Heel touches toe line', 'Arms out gaze forward', 'Turn around repeat'], 'Slow precise.', '20 steps', 'Beginner'),
('Tree Pose', 'balance', 3, 'Yoga pose strengthens balance focus.', ARRAY['Root foot inner thigh/calf', 'Prayer hands gaze fixed', 'Switch sides'], 'Hips square tall.', '30s each side', 'Intermediate'),
('Tai Chi Movements', 'balance', 4, 'Slow controlled motions improve body control.', ARRAY['Weight shifts', 'Arm circles palm changes', 'Silk reeling'], 'Rooted breath centered.', '5 minutes', 'Beginner'),
('Balance Board Exercise', 'balance', 6, 'Standing unstable surface train balance.', ARRAY['Feet shoulder width knees soft', 'Tiny shifts maintain', 'Progress eyes closed'], 'Core engaged catch wobbles.', '2 minutes', 'Intermediate'),
('Flamingo Stand', 'balance', 2, 'Holding one leg up maintaining posture.', ARRAY['Other foot back calf', 'Arms forward parallel floor', 'Gaze forward'], 'Tall chest open.', '30s each side', 'Beginner'),
('Side Leg Raises', 'balance', 5, 'Lifting one leg sideways improve stability.', ARRAY['Standing lift top leg', 'Hips stacked toe point', 'Lower control'], 'Hold wall if needed.', '12 reps each side', 'Intermediate'),
('Tightrope Walk', 'balance', 3, 'Walking rope enhance balance.', ARRAY['Imaginary line heel toe', 'Arms steady side', 'Turn pivot'], 'Focus ahead deliberate.', '30 steps', 'Beginner'),
('Single-Leg Deadlift', 'balance', 7, 'Balancing one leg bending forward.', ARRAY['Hinge hip back straight', 'Reach floor opposite hand', 'Knee soft return'], 'Slow control.', '10 reps each', 'Intermediate'),
('Standing March', 'balance', 3, 'Alternately lifting knees standing still.', ARRAY['Slow high knees', 'Arms opposite swing', 'Gaze fixed'], 'Controlled no lean.', '1 minute', 'Beginner'),
('Bosu Ball Balance', 'balance', 4, 'Standing Bosu ball challenge stability.', ARRAY['Dome up feet shoulder width', 'Knees micro bend', 'Single leg progressions'], 'Catch small corrections.', '1 minute', 'Intermediate'),
('One-Leg Squat', 'balance', 9, 'Squatting one leg build strength balance.', ARRAY['Other leg forward', 'Lower control knee tracks toe', 'Stand full extension'], 'Wall assist first.', '5-8 each side', 'Advanced'),
('Toe Stand', 'balance', 4, 'Standing toes improve lower leg balance.', ARRAY['Lift heels forearms support', 'Gaze forward hips over ankles'], 'Build calf endurance.', '30s hold', 'Intermediate'),
('Stability Ball Exercises', 'balance', 5, 'Using ball engage stabilizing muscles.', ARRAY['Ball between feet wall sit', 'Kneeling ball rollouts', 'Supine leg circles'], 'Controlled smooth.', '3 sets', 'Intermediate'),
('Warrior III Pose', 'balance', 4, 'Leaning forward one leg improve balance.', ARRAY['Lift back leg parallel floor', 'Hinge torso arms forward', 'T position'], 'Core gaze down.', '20s each side', 'Intermediate'),
('Step Balance Hold', 'balance', 3, 'Holding balance after stepping platform.', ARRAY['Step up single leg hold', 'Arms out knees soft', 'Step down slow'], 'Stable landing.', '30s each leg', 'Beginner'),
('Lunge Hold', 'balance', 5, 'Holding lunge position improve stability.', ARRAY['90° both knees torso upright', 'Back heel lifted', 'Micro bounces optional'], 'Hips square forward gaze.', '45s each side', 'Intermediate'),
('Bird Dog', 'balance', 3, 'Extending opposite arm leg improve coordination.', ARRAY['Tabletop extend right arm left leg', 'Parallel floor square hips', 'Hold return alternate'], 'No rotation breathe.', '10 reps each side', 'Beginner'),
('Eyes-Closed Balance', 'balance', 2, 'Balancing without visual input challenge stability.', ARRAY['Single leg or tree', 'Close eyes 10-20s', 'Open adjust repeat'], 'Proprioception training.', '3 sets 15s', 'Intermediate'),
('Clock Reach', 'balance', 4, 'Reaching directions balancing one leg.', ARRAY['12 3 6 9 o''clock reaches', 'Controlled smooth', 'Return center'], 'Single leg stable base.', '5 reps each direction', 'Intermediate')
ON CONFLICT (id) DO NOTHING;

-- Run: psql -d your_db -f all_exercises.sql
-- Ready for ExerciseScreen queries!
