-- Fixed seed_meals.sql - all commas added, syntax valid
INSERT INTO meals (name, category, calories, benefits, foods) VALUES
('Green Smoothie Bowl', 'weight_loss', 280, 'Low calorie, high fiber, detoxifying. Supports weight loss with nutrient-dense ingredients that keep you full longer.', ARRAY['Spinach', 'Cucumber', 'Green apple', 'Celery', 'Protein powder']),
('Cauliflower Rice Bowl', 'weight_loss', 320, 'Low carb alternative to rice, high in vitamins C and K. Supports fat loss while providing essential nutrients.', ARRAY['Cauliflower', 'Grilled chicken', 'Vegetables', 'Low-sodium soy sauce']),
('Zucchini Noodles', 'weight_loss', 250, 'Very low calories, high water content, gluten-free. Satisfying without the carb overload.', ARRAY['Zucchini', 'Turkey meatballs', 'Marinara sauce', 'Parmesan']),
('Grilled Fish Tacos', 'weight_loss', 340, 'High protein, healthy fats, fresh toppings. Satisfying Mexican-inspired meal under 400 calories.', ARRAY['White fish', 'Corn tortillas', 'Cabbage', 'Lime', 'Cilantro']),
('Mass Gainer Shake', 'muscle_gain', 650, 'High protein and calorie content for muscle building. Contains fast and slow-digesting proteins.', ARRAY['Protein powder', 'Banana', 'Oats', 'Peanut butter', 'Whole milk']),
('Beef Steak Dinner', 'muscle_gain', 720, 'Complete protein with iron and zinc. Essential for muscle repair and growth after intense workouts.', ARRAY['8 oz ribeye steak', 'Sweet potato', 'Asparagus', 'Butter']),
('Chicken Rice Bowl', 'muscle_gain', 580, 'Classic muscle building meal with lean protein and complex carbs for energy and recovery.', ARRAY['Chicken breast', 'Brown rice', 'Broccoli', 'Egg']),
('Egg White Omelet', 'muscle_gain', 320, 'Pure protein without excess fats. Perfect for lean muscle building.', ARRAY['Egg whites', 'Turkey bacon', 'Cheese', 'Spinach']),
('Mediterranean Plate', 'balanced', 480, 'Balanced macros with healthy fats, lean protein, and complex carbs. Supports overall health.', ARRAY['Grilled chicken', 'Quinoa', 'Hummus', 'Cucumber', 'Olives']),
('Asian Fusion Bowl', 'balanced', 520, 'Well-rounded with protein, vegetables, and carbs. Good mix of nutrients for daily energy.', ARRAY['Tofu', 'Brown rice', 'Edamame', 'Carrots', 'Ginger dressing']),
('American Classic', 'balanced', 550, 'Complete meal with all food groups. Provides sustained energy and satisfaction.', ARRAY['Grilled chicken', 'Whole wheat bread', 'Vegetables', 'Fruit']),
('Continental Breakfast', 'balanced', 420, 'Morning balance of protein, carbs, and fruits. Great start to the day.', ARRAY['Eggs', 'Whole grain toast', 'Yogurt', 'Fresh fruits', 'Juice']),
('Keto Steak Bowl', 'low_carb', 580, 'Very low carbs, high fat and protein. Puts body in fat-burning state.', ARRAY['Ribeye steak', 'Bacon', 'Avocado', 'Eggs', 'Cheese']),
('Tuna Salad Bowl', 'low_carb', 320, 'Very low carb, high protein. Perfect for low-carb dieters.', ARRAY['Canned tuna', 'Mayo', 'Celery', 'Lettuce', 'Avocado']),
('Chicken Caesar Salad', 'low_carb', 450, 'Low carb with protein. Classic restaurant favorite made healthier.', ARRAY['Grilled chicken', 'Romaine lettuce', 'Parmesan', 'Caesar dressing']),
('Protein Pack', 'high_protein', 480, 'Extremely high protein content. Perfect for post-workout recovery.', ARRAY['Chicken breast', 'Greek yogurt', 'Cottage cheese', 'Egg whites']),
('Seafood Platter', 'high_protein', 420, 'High protein from fish and shellfish. Low in fat, high in omega-3s.', ARRAY['Shrimp', 'Salmon', 'Crab', 'Lime', 'Cocktail sauce']),
('Cottage Cheese Plate', 'high_protein', 280, 'Quick high protein snack or meal. Contains casein protein for sustained release.', ARRAY['Cottage cheese', 'Almonds', 'Berries', 'Honey']),
('Grilled Chicken with Vegetables', 'balanced', 400, 'Balanced protein and nutrients.', ARRAY['Chicken Breast', 'Broccoli', 'Carrots']),
('Oatmeal with Fruits', 'balanced', 350, 'Provides energy and fiber.', ARRAY['Oats', 'Bananas', 'Strawberries']),
('Salmon with Brown Rice', 'balanced', 450, 'Supports heart health and recovery.', ARRAY['Salmon', 'Brown Rice']),
('Vegetable Stir-Fry', 'weight_loss', 250, 'Low-calorie and nutrient-rich meal.', ARRAY['Bell Peppers', 'Broccoli', 'Zucchini']),
('Chicken Salad', 'weight_loss', 350, 'Light meal rich in protein.', ARRAY['Chicken Breast', 'Tomatoes', 'Cucumber']),
('Egg and Toast', 'balanced', 300, 'Simple and energizing breakfast.', ARRAY['Eggs', 'Brown Bread']),
('Quinoa Bowl', 'balanced', 400, 'High in protein and fiber.', ARRAY['Quinoa', 'Spinach', 'Avocado']),
('Tuna Sandwich', 'balanced', 380, 'Healthy and convenient meal.', ARRAY['Tuna', 'Brown Bread', 'Tomatoes']),
('Vegetable Soup', 'weight_loss', 200, 'Warm and low in calories.', ARRAY['Carrots', 'Tomatoes', 'Spinach']),
('Grilled Fish with Salad', 'weight_loss', 350, 'Supports weight management.', ARRAY['Salmon', 'Cucumber', 'Tomatoes']),
('Brown Rice with Lean Meat', 'muscle_gain', 500, 'Builds muscle and energy.', ARRAY['Brown Rice', 'Lean Beef', 'Broccoli']),
('Smoothie Bowl', 'balanced', 320, 'Rich in vitamins and antioxidants.', ARRAY['Bananas', 'Blueberries', 'Greek Yogurt']),
('Chicken Wrap', 'balanced', 400, 'Balanced and portable meal.', ARRAY['Chicken Breast', 'Brown Bread', 'Vegetables']),
('Pasta with Tomato Sauce', 'balanced', 450, 'Provides carbohydrates for energy.', ARRAY['Whole Grain Pasta', 'Tomatoes']),
('Egg Fried Rice', 'balanced', 420, 'Balanced protein and carbs.', ARRAY['Eggs', 'Brown Rice', 'Vegetables']),
('Baked Sweet Potato with Chicken', 'balanced', 450, 'Supports recovery.', ARRAY['Sweet Potatoes', 'Chicken Breast']),
('Avocado Toast', 'balanced', 320, 'Provides healthy fats.', ARRAY['Avocado', 'Brown Bread']),
('Lentil Soup', 'balanced', 300, 'Plant-based protein meal.', ARRAY['Lentils', 'Carrots', 'Tomatoes']),
('Grilled Shrimp with Veggies', 'weight_loss', 350, 'Low-fat protein meal.', ARRAY['Shrimp', 'Broccoli', 'Bell Peppers']),
('Rice and Beans', 'balanced', 400, 'Balanced and affordable meal.', ARRAY['Brown Rice', 'Beans']),
('Beef and Broccoli', 'muscle_gain', 450, 'Protein with fiber-rich veggies.', ARRAY['Lean Beef', 'Broccoli']),
('Turkey Sandwich', 'balanced', 380, 'Lean and filling meal.', ARRAY['Turkey', 'Brown Bread']),
('Veggie Omelette', 'balanced', 350, 'Protein with vitamins.', ARRAY['Eggs', 'Spinach', 'Tomatoes']),
('Chicken Pasta', 'balanced', 480, 'Balanced carbs and protein.', ARRAY['Chicken Breast', 'Whole Grain Pasta']),
('Fish Tacos', 'balanced', 400, 'Light and flavorful meal.', ARRAY['Salmon', 'Corn']),
('Stir-Fried Tofu', 'balanced', 350, 'Plant-based protein option.', ARRAY['Tofu', 'Bell Peppers', 'Zucchini']),
('Chicken Curry with Rice', 'balanced', 500, 'Energy and protein rich meal.', ARRAY['Chicken Breast', 'Brown Rice']),
('Shrimp Fried Rice', 'balanced', 420, 'Balanced and satisfying.', ARRAY['Shrimp', 'Brown Rice']),
('Breakfast Burrito', 'balanced', 450, 'Protein-packed breakfast meal.', ARRAY['Eggs', 'Turkey', 'Brown Bread']),
('Yogurt with Granola', 'balanced', 350, 'Supports digestion and energy.', ARRAY['Yogurt', 'Oats']),
('Fruit Salad', 'balanced', 250, 'Refreshing and vitamin-rich meal.', ARRAY['Apples', 'Oranges', 'Strawberries']),
('Chicken Noodle Soup', 'balanced', 380, 'Comforting and nutritious.', ARRAY['Chicken Breast', 'Carrots']),
('Grilled Steak with Veggies', 'muscle_gain', 550, 'High protein meal.', ARRAY['Lean Beef', 'Broccoli']),
('Veggie Pizza (Healthy)', 'balanced', 400, 'Balanced treat with nutrients.', ARRAY['Tomatoes', 'Bell Peppers', 'Cheese']),
('Baked Fish with Potatoes', 'balanced', 450, 'Supports energy and recovery.', ARRAY['Salmon', 'Sweet Potatoes']),
('Chicken Caesar Salad', 'weight_loss', 380, 'Protein-rich light meal.', ARRAY['Chicken Breast', 'Spinach']),
('Egg Salad Sandwich', 'balanced', 400, 'Simple protein meal.', ARRAY['Eggs', 'Brown Bread']),
('Rice with Grilled Pork', 'balanced', 480, 'Provides energy and protein.', ARRAY['Brown Rice']),
('Tofu and Vegetable Bowl', 'balanced', 350, 'Plant-based balanced meal.', ARRAY['Tofu', 'Broccoli', 'Carrots']),
('Pasta Salad', 'balanced', 380, 'Light and refreshing.', ARRAY['Whole Grain Pasta', 'Tomatoes']),
('Chicken and Rice Bowl', 'balanced', 450, 'Balanced daily meal.', ARRAY['Chicken Breast', 'Brown Rice']),
('Fish Soup', 'balanced', 300, 'Supports heart health.', ARRAY['Salmon', 'Tomatoes']),
('Veggie Wrap', 'weight_loss', 320, 'Healthy and convenient.', ARRAY['Vegetables', 'Tofu']),
('Beef Tacos', 'muscle_gain', 450, 'Protein-rich and filling.', ARRAY['Lean Beef', 'Corn']),
('Grilled Corn with Chicken', 'balanced', 420, 'Balanced carbs and protein.', ARRAY['Corn', 'Chicken Breast']),
('Omelette with Vegetables', 'balanced', 350, 'Nutritious breakfast.', ARRAY['Eggs', 'Spinach', 'Tomatoes']),
('Baked Chicken with Rice', 'muscle_gain', 480, 'Supports muscle growth.', ARRAY['Chicken Breast', 'Brown Rice']),
('Shrimp Salad', 'weight_loss', 320, 'Light and protein-rich.', ARRAY['Shrimp', 'Cucumber']),
('Lentil and Rice Bowl', 'balanced', 400, 'Plant-based balanced meal.', ARRAY['Lentils', 'Brown Rice']),
('Mixed Vegetable Curry', 'balanced', 350, 'Rich in nutrients and fiber.', ARRAY['Carrots', 'Bell Peppers', 'Zucchini'])
ON CONFLICT (id) DO NOTHING;
