-- Seed foods data (extracted from RecipesScreen.tsx FOOD_DATABASE)
-- Run after creating foods table: CREATE TABLE foods (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT, category TEXT, calories INTEGER, benefits TEXT);

INSERT INTO foods (name, category, calories, benefits) VALUES
('Apple', 'fruits', 95, 'Good source of fiber, vitamin C, and antioxidants. Helps improve digestion and heart health.'),
('Banana', 'fruits', 105, 'Rich in potassium, vitamin B6, and fiber. Provides quick energy and supports muscle function.'),
('Orange', 'fruits', 62, 'Excellent source of vitamin C, fiber, and folate. Boosts immune system.'),
('Strawberries', 'fruits', 49, 'Low in calories, high in antioxidants, vitamin C, and manganese.'),
('Blueberries', 'fruits', 84, 'Packed with antioxidants, vitamins C and K. Supports brain health.'),
('Broccoli', 'vegetables', 55, 'Rich in fiber, vitamin C, and cancer-fighting compounds. Supports bone health.'),
('Spinach', 'vegetables', 23, 'High in iron, vitamins A, C, and K. Great for eye health and blood pressure.'),
('Carrots', 'vegetables', 25, 'Excellent source of beta-carotene, fiber, and vitamin A. Promotes eye health.'),
('Bell Pepper', 'vegetables', 31, 'High in vitamin C, antioxidants, and capsaicin. Boosts metabolism.'),
('Tomato', 'vegetables', 22, 'Contains lycopene, vitamin C, and potassium. Supports heart health.'),
('Brown Rice', 'grains', 216, 'Whole grain high in fiber, manganese, and selenium. Supports digestion.'),
('Oatmeal', 'grains', 158, 'High in fiber, beta-glucan, and antioxidants. Lowers cholesterol levels.'),
('Quinoa', 'grains', 222, 'Complete protein with all essential amino acids. Gluten-free and high in fiber.'),
('Whole Wheat Bread', 'grains', 81, 'Good source of fiber, B vitamins, and iron. Sustains energy levels.'),
('Sweet Potato', 'grains', 103, 'Rich in beta-carotene, fiber, and vitamin C. Stabilizes blood sugar.'),
('Chicken Breast', 'protein', 165, 'Lean protein source, low in fat. Supports muscle growth and repair.'),
('Salmon', 'protein', 208, 'Rich in omega-3 fatty acids, protein, and vitamin D. Supports heart and brain health.'),
('Eggs', 'protein', 155, 'Complete protein with all essential amino acids. Rich in choline and vitamin D.'),
('Greek Yogurt', 'protein', 100, 'High protein, contains probiotics for gut health. Rich in calcium.'),
('Lentils', 'protein', 230, 'Plant-based protein high in fiber, iron, and folate. Supports heart health.'),
('Milk', 'dairy', 149, 'Good source of calcium, protein, and vitamin D. Strengthens bones.'),
('Cheese', 'dairy', 113, 'High in calcium, protein, and vitamin B12. Supports bone health.'),
('Cottage Cheese', 'dairy', 163, 'Low-fat, high-protein dairy product. Rich in B vitamins and selenium.'),
('Almond Milk', 'dairy', 39, 'Dairy-free, low in calories, fortified with calcium and vitamin D.'),
('Greek Yogurt', 'dairy', 100, 'High protein, probiotics for gut health. Excellent source of calcium.'),
('Brown Rice', 'grains', 111, 'A whole grain that provides long-lasting energy and fiber.'),
('Oats', 'grains', 389, 'Supports digestion and helps maintain heart health.'),
('Chicken Breast', 'protein', 165, 'A lean protein that helps build muscle.'),
('Eggs', 'protein', 143, 'Rich in protein and essential nutrients for body repair.'),
('Bananas', 'fruits', 89, 'Provide quick energy and potassium.'),
('Apples', 'fruits', 52, 'Aid digestion with fiber and antioxidants.'),
('Spinach', 'vegetables', 23, 'Packed with iron and vitamins for energy.'),
('Broccoli', 'vegetables', 34, 'Supports immunity with fiber and nutrients.'),
('Sweet Potatoes', 'grains', 86, 'Provide healthy carbohydrates for energy.'),
('Almonds', 'protein', 579, 'Contain healthy fats and protein.'),
('Avocado', 'vegetables', 160, 'Provides heart-healthy fats.'),
('Quinoa', 'grains', 120, 'A complete protein grain for muscle repair.'),
('Tuna', 'protein', 132, 'Lean protein that supports muscle growth.'),
('Carrots', 'vegetables', 41, 'Support eye health with vitamins.'),
('Tomatoes', 'vegetables', 18, 'Rich in antioxidants for body protection.'),
('Cucumber', 'vegetables', 16, 'Hydrating and low in calories.'),
('Beans', 'protein', 127, 'Provide fiber and plant-based protein.'),
('Milk', 'dairy', 42, 'Supports strong bones with calcium.'),
('Cheese', 'dairy', 402, 'Provides calcium and protein.'),
('Yogurt', 'dairy', 61, 'Aids digestion with probiotics.'),
('Brown Bread', 'grains', 250, 'A healthier source of carbohydrates.'),
('Peanuts', 'protein', 567, 'Provide protein and healthy fats.'),
('Cashews', 'protein', 553, 'Supply energy and nutrients.'),
('Oranges', 'fruits', 47, 'Boost immunity with vitamin C.'),
('Mangoes', 'fruits', 60, 'Provide vitamins and natural sugars.'),
('Pineapple', 'fruits', 50, 'Supports digestion with enzymes.'),
('Watermelon', 'fruits', 30, 'Hydrates and refreshes the body.'),
('Grapes', 'fruits', 69, 'Provide antioxidants for heart health.'),
('Strawberries', 'fruits', 32, 'Support skin and immune health.'),
('Blueberries', 'fruits', 57, 'Known for high antioxidant content.'),
('Egg Whites', 'protein', 52, 'Low-fat protein for muscle building.'),
('Lean Beef', 'protein', 250, 'Provides iron and protein.'),
('Turkey', 'protein', 189, 'A lean protein source for muscle growth.'),
('Tofu', 'protein', 76, 'A plant-based protein option.'),
('Lentils', 'protein', 116, 'High in fiber and protein.'),
('Chickpeas', 'protein', 164, 'Support digestion and energy.'),
('Olive Oil', 'vegetables', 884, 'Healthy fat that supports heart health.'),
('Coconut Water', 'fruits', 19, 'Hydrates and replenishes electrolytes.'),
('Dark Chocolate', 'dairy', 546, 'Contains antioxidants in moderation.'),
('Green Tea', 'fruits', 1, 'Supports metabolism and fat burning.'),
('Whole Grain Pasta', 'grains', 131, 'Provides sustained energy.'),
('Corn', 'grains', 86, 'A source of carbohydrates and fiber.'),
('Mushrooms', 'vegetables', 22, 'Provide vitamins and support immunity.'),
('Bell Peppers', 'vegetables', 20, 'Rich in vitamins and antioxidants.'),
('Zucchini', 'vegetables', 17, 'Low-calorie vegetable rich in nutrients.'),
('Kale', 'vegetables', 49, 'A superfood high in vitamins and minerals.'),
('Pumpkin Seeds', 'protein', 446, 'Provide magnesium and healthy fats.'),
('Sunflower Seeds', 'protein', 584, 'Support heart health with nutrients.')
ON CONFLICT (id) DO NOTHING;

