-- Seed recipes data (extracted from RecipesScreen.tsx RECIPE_DATABASE)
-- Run this after creating tables

INSERT INTO recipes (name, category, calories, prep_time, ingredients, instructions, benefits) VALUES
('Oatmeal with Berries', 'breakfast', 350, '10 min', ARRAY['1 cup rolled oats', '1 cup almond milk', '1/2 cup mixed berries', '1 tbsp honey', '1/4 cup almonds'], ARRAY['Cook oats with almond milk', 'Top with berries and almonds', 'Drizzle with honey'], 'High in fiber, supports heart health, provides sustained energy throughout the morning.'),
('Egg White Scramble', 'breakfast', 200, '15 min', ARRAY['4 egg whites', '1/4 cup spinach', '1/4 cup mushrooms', '1/4 cup tomatoes', 'Salt and pepper'], ARRAY['Whisk egg whites', 'Sauté vegetables', 'Combine and scramble', 'Season to taste'], 'Low in calories, high in protein, supports muscle maintenance.'),
('Greek Yogurt Parfait', 'breakfast', 280, '5 min', ARRAY['1 cup Greek yogurt', '1/2 cup granola', '1/2 cup fresh fruits', '1 tbsp honey'], ARRAY['Layer yogurt in a glass', 'Add granola layer', 'Top with fruits', 'Drizzle honey'], 'Rich in probiotics, calcium, and protein for gut health.'),
('Avocado Toast', 'breakfast', 320, '10 min', ARRAY['2 slices whole wheat bread', '1 avocado', '2 eggs', 'Salt, pepper, red pepper flakes'], ARRAY['Toast bread', 'Mash avocado with salt', 'Spread on toast', 'Top with poached eggs'], 'Healthy fats, fiber, and protein for a balanced breakfast.'),
('Grilled Chicken Salad', 'lunch', 420, '25 min', ARRAY['6 oz chicken breast', '2 cups mixed greens', '1/2 cucumber', '1/2 tomatoes', '2 tbsp olive oil dressing'], ARRAY['Grill chicken breast', 'Prepare vegetables', 'Combine in bowl', 'Drizzle with dressing'], 'High protein, low carbs, supports muscle building and satiety.'),
('Quinoa Buddha Bowl', 'lunch', 480, '30 min', ARRAY['1 cup quinoa', '1/2 cup chickpeas', '1/2 avocado', '1/2 cup roasted vegetables', 'Tahini dressing'], ARRAY['Cook quinoa', 'Roast vegetables', 'Assemble bowl', 'Add tahini dressing'], 'Complete protein, fiber-rich, supports digestive health.'),
('Turkey Wrap', 'lunch', 350, '15 min', ARRAY['4 oz turkey breast', '1 whole wheat wrap', '1 slice cheese', 'Lettuce', 'Tomato', 'Mustard'], ARRAY['Lay out wrap', 'Add turkey and cheese', 'Add vegetables', 'Roll tightly'], 'Lean protein, complex carbs, satisfying and nutritious.'),
('Salmon Poke Bowl', 'lunch', 520, '20 min', ARRAY['5 oz salmon', '1 cup rice', '1/2 avocado', 'Edamame', 'Cucumber', 'Soy sauce'], ARRAY['Cook rice', 'Cube salmon', 'Prepare vegetables', 'Assemble bowl', 'Drizzle soy sauce'], 'Omega-3 fatty acids, high protein, supports brain health.'),
('Baked Salmon with Vegetables', 'dinner', 450, '35 min', ARRAY['6 oz salmon fillet', '1 cup broccoli', '1 cup carrots', '2 tbsp olive oil', 'Lemon', 'Garlic'], ARRAY['Preheat oven', 'Season salmon', 'Arrange vegetables', 'Bake at 400°F for 25 min'], 'Heart-healthy omega-3s, anti-inflammatory, rich in vitamins.'),
('Chicken Stir Fry', 'dinner', 380, '25 min', ARRAY['6 oz chicken breast', '2 cups mixed vegetables', '2 tbsp soy sauce', '1 tbsp sesame oil', 'Ginger', 'Garlic'], ARRAY['Cut chicken into strips', 'Stir fry vegetables', 'Add chicken', 'Season with sauces'], 'High protein, low fat, quick and easy meal option.'),
('Beef and Broccoli', 'dinner', 520, '30 min', ARRAY['6 oz beef sirloin', '2 cups broccoli', '2 tbsp soy sauce', '1 tbsp oyster sauce', 'Garlic'], ARRAY['Slice beef thinly', 'Stir fry beef', 'Add broccoli', 'Add sauces and simmer'], 'High iron, protein-rich, supports blood health.'),
('Vegetable Pasta', 'dinner', 420, '25 min', ARRAY['2 oz whole wheat pasta', '2 cups vegetables', '2 tbsp olive oil', 'Parmesan cheese', 'Italian herbs'], ARRAY['Cook pasta', 'Sauté vegetables', 'Toss together', 'Top with cheese'], 'Complex carbs, fiber, and antioxidants.'),
('Mixed Nuts', 'snacks', 180, '0 min', ARRAY['1 oz almonds', '1 oz walnuts', '1 oz cashews'], ARRAY['Combine nuts in a small container', 'Portion into servings'], 'Healthy fats, protein, and minerals for energy.'),
('Apple with Peanut Butter', 'snacks', 200, '2 min', ARRAY['1 medium apple', '2 tbsp peanut butter'], ARRAY['Slice apple', 'Serve with peanut butter'], 'Fiber, protein, and natural sugars for quick energy.'),
('Protein Smoothie', 'snacks', 250, '5 min', ARRAY['1 scoop protein powder', '1 banana', '1 cup almond milk', 'Ice'], ARRAY['Add all ingredients to blender', 'Blend until smooth'], 'Quick protein, post-workout recovery, convenient nutrition.'),
('Dark Chocolate', 'desserts', 170, '0 min', ARRAY['1 oz dark chocolate (70%+)'], ARRAY['Enjoy in moderation'], 'Antioxidants, may improve heart health, satisfies cravings.'),
('Frozen Banana Bites', 'desserts', 120, '10 min', ARRAY['1 banana', '2 tbsp dark chocolate chips', '1 tbsp crushed nuts'], ARRAY['Slice banana', 'Dip in chocolate', 'Top with nuts', 'Freeze for 2 hours'], 'Natural sweetness, potassium, guilt-free treat.'),
('Chia Pudding', 'desserts', 200, '5 min', ARRAY['3 tbsp chia seeds', '1 cup coconut milk', '1 tbsp maple syrup', 'Fresh fruits'], ARRAY['Mix chia seeds with milk', 'Add maple syrup', 'Refrigerate overnight', 'Top with fruits'], 'Omega-3s, fiber, supports digestive health.')
ON CONFLICT DO NOTHING;

