-- Seed recipes data (extracted from RecipesScreen.tsx RECIPE_DATABASE)
-- Run this after creating tables

INSERT INTO recipes (name, category, calories, prep_time, ingredients, instructions, benefits) VALUES
('Oatmeal with Berries', 'breakfast', 350, '10 min', ARRAY['1 cup rolled oats', '1 cup almond milk', '1/2 cup mixed berries', '1 tbsp honey', '1/4 cup almonds'], ARRAY['Cook oats with almond milk', 'Top with berries and almonds', 'Drizzle with honey'], 'High in fiber, supports heart health, provides sustained energy throughout the morning.'),
('Egg White Scramble', 'breakfast', 200, '15 min', ARRAY['4 egg whites', '1/4 cup spinach', '1/4 cup mushrooms', '1/4 cup tomatoes', 'Salt and pepper'], ARRAY['Whisk egg whites', 'Sauté vegetables', 'Combine and scramble', 'Season to taste'], 'Low in calories, high in protein, supports muscle maintenance.'),
('Greek Yogurt Parfait', 'breakfast', 280, '5 min', ARRAY['1 cup Greek yogurt', '1/2 cup granola', '1/2 cup fresh fruits', '1 tbsp honey'], ARRAY['Layer yogurt in a glass', 'Add granola layer', 'Top with fruits', 'Drizzle honey'], 'Rich in probiotics, calcium, and protein for gut health.'),
('Avocado Toast', 'breakfast', 320, '10 min', ARRAY['2 slices whole wheat bread', '1 avocado', '2 eggs', 'Salt, pepper, red pepper flakes'], ARRAY['Toast bread', 'Mash avocado with salt', 'Spread on toast', 'Top with poached eggs'], 'Healthy fats, fiber, and protein for a balanced breakfast.'),
('Grilled Chicken Salad', 'lunch', 420, '25 min', ARRAY['6 oz chicken breast', '2 cups mixed greens', '1/2 cucumber', '1/2 tomatoes', '2 tbsp olive oil dressing'], ARRAY['Grill chicken breast', 'Prepare vegetables', 'Combine in bowl', 'Drizzle with dressing'], 'High protein, low carbs, supports muscle building and satiety.'),
('Quinoa Buddha Bowl', 'lunch', 480, '30 min', ARRAY['1 cup quinoa', '1/2 cup chickpeas', '1/2 avocado', '1/2 cup roasted vegetables', 'Tahini dressing'], ARRAY['Cook quinoa', 'Roast vegetables', 'Assemble bowl', 'Add tahini dressing'], 'Complete protein, fiber-rich, supports digestive health.'),
('Turkey Wrap', 'lunch', 350, '15 min', ARRAY['4 oz turkey breast', '1 whole wheat wrap', '1 slice cheese', 'Lettuce', 'Tomato', 'Mustard'], ARRAY['Lay out wrap', 'Add turkey and cheese', 'Add vegetables', 'Roll tightly'], 'Lean protein, complex carbs, satisfying and nutritious.'),
('Salmon Poke Bowl', 'lunch', 520, '20 min', ARRAY['5 oz salmon', '1 cup rice', '1/2 avocado', 'Edamame', 'Cucumber', 'Soy sauce'], ARRAY['Cook rice', 'Cube salmon', 'Prepare vegetables', 'Assemble bowl', 'Drizzle soy sauce'], 'Omega-3 fatty acids, high protein, supports brain health.'),
('Baked Salmon with Vegetables', 'dinner', 450, '35 min', ARRAY['6 oz salmon fillet', '1 cup broccoli', '1 cup carrots', '2 tbsp olive oil', 'Lemon', 'Garlic'], ARRAY['Preheat oven', 'Season salmon', 'Arrange vegetables', 'Bake at 400°F for 25 min'], 'Heart-healthy omega-3s, anti-inflammatory, rich in vitamins.'),
('Chicken Stir Fry', 'dinner', 380, '25 min', ARRAY['6 oz chicken breast', '2 cups mixed vegetables', '2 tbsp soy sauce', '1 tbsp sesame oil', 'Ginger', 'Garlic'], ARRAY['Cut chicken into strips', 'Stir fry vegetables', 'Add chicken', 'Season with sauces'], 'High protein, low fat, quick and easy meal option.'),
('Beef and Broccoli', 'dinner', 520, '30 min', ARRAY['6 oz beef sirloin', '2 cups broccoli', '2 tbsp soy sauce', '1 tbsp oyster sauce', 'Garlic'], ARRAY['Slice beef thinly', 'Stir fry beef', 'Add broccoli', 'Add sauces and simmer'], 'High iron, protein-rich, supports blood health.'),
('Vegetable Pasta', 'dinner', 420, '25 min', ARRAY['2 oz whole wheat pasta', '2 cups vegetables', '2 tbsp olive oil', 'Parmesan cheese', 'Italian herbs'], ARRAY['Cook pasta', 'Sauté vegetables', 'Toss together', 'Top with cheese'], 'Complex carbs, fiber, and antioxidants.'),
('Mixed Nuts', 'snacks', 180, '0 min', ARRAY['1 oz almonds', '1 oz walnuts', '1 oz cashews'], ARRAY['Combine nuts in a small container', 'Portion into servings'], 'Healthy fats, protein, and minerals for energy.'),
('Apple with Peanut Butter', 'snacks', 200, '2 min', ARRAY['1 medium apple', '2 tbsp peanut butter'], ARRAY['Slice apple', 'Serve with peanut butter'], 'Fiber, protein, and natural sugars for quick energy.'),
('Protein Smoothie', 'snacks', 250, '5 min', ARRAY['1 scoop protein powder', '1 banana', '1 cup almond milk', 'Ice'], ARRAY['Add all ingredients to blender', 'Blend until smooth'], 'Quick protein, post-workout recovery, convenient nutrition.'),
('Dark Chocolate', 'desserts', 170, '0 min', ARRAY['1 oz dark chocolate (70%+)'], ARRAY['Enjoy in moderation'], 'Antioxidants, may improve heart health, satisfies cravings.'),
('Frozen Banana Bites', 'desserts', 120, '10 min', ARRAY['1 banana', '2 tbsp dark chocolate chips', '1 tbsp crushed nuts'], ARRAY['Slice banana', 'Dip in chocolate', 'Top with nuts', 'Freeze for 2 hours'], 'Natural sweetness, potassium, guilt-free treat.'),
('Chia Pudding', 'desserts', 200, '5 min', ARRAY['3 tbsp chia seeds', '1 cup coconut milk', '1 tbsp maple syrup', 'Fresh fruits'], ARRAY['Mix chia seeds with milk', 'Add maple syrup', 'Refrigerate overnight', 'Top with fruits'], 'Omega-3s, fiber, supports digestive health.'), 
('Banana Oat Pancakes', 'breakfast', 300, '15 min', ARRAY['2 bananas', '1 cup oats', '2 eggs', '1 tsp baking powder'], ARRAY['Mash bananas', 'Mix with oats and eggs', 'Cook on pan'], 'Healthy breakfast with natural ingredients.'),
('Grilled Chicken Salad', 'lunch', 400, '20 min', ARRAY['Chicken Breast', 'Spinach', 'Tomatoes', 'Cucumber'], ARRAY['Grill chicken', 'Chop vegetables', 'Mix with dressing'], 'Combines protein and vegetables.'),
('Vegetable Omelette', 'breakfast', 350, '10 min', ARRAY['Eggs', 'Bell Peppers', 'Spinach', 'Tomatoes'], ARRAY['Whisk eggs', 'Add veggies', 'Cook omelette'], 'Protein-rich with added nutrients.'),
('Fruit Smoothie', 'breakfast', 250, '5 min', ARRAY['Bananas', 'Strawberries', 'Greek Yogurt', 'Milk'], ARRAY['Blend all ingredients'], 'Quick and vitamin-rich drink.'),
('Baked Salmon', 'dinner', 450, '25 min', ARRAY['Salmon', 'Olive Oil', 'Lemon', 'Herbs'], ARRAY['Season salmon', 'Bake at 400F'], 'Heart-healthy omega-3 dish.'),
('Chicken Stir-Fry', 'dinner', 400, '15 min', ARRAY['Chicken Breast', 'Broccoli', 'Carrots', 'Soy sauce'], ARRAY['Stir fry chicken and veggies'], 'Balanced protein and vegetables.'),
('Quinoa Salad', 'lunch', 380, '20 min', ARRAY['Quinoa', 'Cucumber', 'Tomatoes', 'Feta'], ARRAY['Cook quinoa', 'Mix with veggies'], 'Light and protein-packed dish.'),
('Tuna Pasta', 'lunch', 450, '20 min', ARRAY['Tuna', 'Whole Grain Pasta', 'Tomatoes'], ARRAY['Cook pasta', 'Mix with tuna sauce'], 'Combines carbs and protein.'),
('Vegetable Soup', 'lunch', 200, '25 min', ARRAY['Carrots', 'Tomatoes', 'Spinach'], ARRAY['Simmer vegetables in broth'], 'Low-calorie nutrient-rich dish.'),
('Egg Muffins', 'breakfast', 300, '20 min', ARRAY['Eggs', 'Spinach', 'Cheese'], ARRAY['Mix and bake in muffin tin'], 'Portable protein snack.'),
('Avocado Toast with Egg', 'breakfast', 350, '10 min', ARRAY['Avocado', 'Brown Bread', 'Eggs'], ARRAY['Toast bread', 'Add avocado and egg'], 'Balanced fats and protein.'),
('Chicken Wrap', 'lunch', 400, '10 min', ARRAY['Chicken Breast', 'Brown Bread', 'Vegetables'], ARRAY['Fill wrap and roll'], 'Easy and nutritious meal.'),
('Baked Sweet Potato Fries', 'snacks', 250, '25 min', ARRAY['Sweet Potatoes', 'Olive Oil'], ARRAY['Slice and bake'], 'Healthy snack alternative.'),
('Yogurt Parfait', 'breakfast', 320, '5 min', ARRAY['Greek Yogurt', 'Granola', 'Berries'], ARRAY['Layer ingredients'], 'Protein and fruit combination.'),
('Energy Balls', 'snacks', 200, '10 min', ARRAY['Oats', 'Peanut Butter', 'Honey'], ARRAY['Mix and roll into balls', 'Chill'], 'Quick energy snack.'),
('Veggie Skewers', 'snacks', 150, '15 min', ARRAY['Bell Peppers', 'Zucchini', 'Mushrooms'], ARRAY['Thread on skewers', 'Grill'], 'Healthy grilled vegetables.'),
('Brown Rice Fried Rice', 'dinner', 400, '20 min', ARRAY['Brown Rice', 'Eggs', 'Vegetables'], ARRAY['Stir fry all together'], 'Healthier version of fried rice.'),
('Spinach Smoothie', 'breakfast', 250, '5 min', ARRAY['Spinach', 'Bananas', 'Milk'], ARRAY['Blend smooth'], 'Nutrient-rich drink.'),
('Lentil Curry', 'dinner', 380, '30 min', ARRAY['Lentils', 'Tomatoes', 'Spices'], ARRAY['Simmer until tender'], 'Protein-rich plant-based dish.'),
('Chicken Vegetable Soup', 'lunch', 350, '25 min', ARRAY['Chicken Breast', 'Carrots', 'Celery'], ARRAY['Simmer in broth'], 'Comforting healthy meal.'),
('Oatmeal Cookies (Healthy)', 'desserts', 150, '20 min', ARRAY['Oats', 'Bananas', 'Raisins'], ARRAY['Mix and bake'], 'Nutritious sweet snack.'),
('Grilled Fish Tacos', 'dinner', 400, '20 min', ARRAY['Fish', 'Corn', 'Cabbage'], ARRAY['Grill fish', 'Assemble tacos'], 'Light and healthy meal.'),
('Veggie Pasta', 'dinner', 420, '20 min', ARRAY['Whole Grain Pasta', 'Zucchini', 'Tomatoes'], ARRAY['Cook pasta with veggies'], 'Balanced and fiber-rich dish.'),
('Chicken Burrito Bowl', 'lunch', 450, '20 min', ARRAY['Chicken Breast', 'Brown Rice', 'Beans'], ARRAY['Layer in bowl'], 'High protein meal.'),
('Smoothie Bowl', 'breakfast', 350, '10 min', ARRAY['Bananas', 'Blueberries', 'Granola'], ARRAY['Blend thick', 'Top with granola'], 'Thick fruit-based healthy meal.'),
('Egg Fried Quinoa', 'dinner', 400, '15 min', ARRAY['Quinoa', 'Eggs', 'Vegetables'], ARRAY['Stir fry together'], 'Protein-rich alternative to rice.'),
('Baked Chicken Tenders', 'dinner', 380, '25 min', ARRAY['Chicken Breast', 'Spices'], ARRAY['Bake until crispy'], 'Healthy version of fried chicken.'),
('Shrimp Stir-Fry', 'dinner', 350, '15 min', ARRAY['Shrimp', 'Broccoli', 'Bell Peppers'], ARRAY['Quick stir fry'], 'Quick and nutritious meal.'),
('Tofu Stir-Fry', 'dinner', 350, '15 min', ARRAY['Tofu', 'Vegetables', 'Soy sauce'], ARRAY['Stir fry all'], 'Plant-based protein dish.'),
('Cauliflower Rice', 'snacks', 150, '10 min', ARRAY['Cauliflower', 'Herbs'], ARRAY['Pulse and sauté'], 'Low-carb rice alternative.'),
('Zucchini Noodles', 'snacks', 100, '10 min', ARRAY['Zucchini'], ARRAY['Spiralize and lightly cook'], 'Healthy pasta substitute.'),
('Turkey Meatballs', 'dinner', 400, '25 min', ARRAY['Turkey', 'Spices'], ARRAY['Bake meatballs'], 'Lean protein dish.'),
('Homemade Granola', 'breakfast', 300, '30 min', ARRAY['Oats', 'Nuts', 'Honey'], ARRAY['Bake mixture'], 'Healthy breakfast topping.'),
('Chickpea Salad', 'lunch', 350, '10 min', ARRAY['Chickpeas', 'Tomatoes', 'Cucumber'], ARRAY['Mix together'], 'Fiber-rich and refreshing dish.'),
('Avocado Smoothie', 'breakfast', 300, '5 min', ARRAY['Avocado', 'Bananas', 'Milk'], ARRAY['Blend smooth'], 'Creamy and nutritious drink.'),
('Baked Fish Fillet', 'dinner', 350, '20 min', ARRAY['Fish', 'Lemon', 'Herbs'], ARRAY['Bake seasoned'], 'Low-fat protein meal.'),
('Sweet Potato Mash', 'snacks', 200, '20 min', ARRAY['Sweet Potatoes'], ARRAY['Boil and mash'], 'Healthy carb side dish.'),
('Chicken Lettuce Wraps', 'lunch', 350, '15 min', ARRAY['Chicken Breast', 'Lettuce', 'Vegetables'], ARRAY['Fill lettuce leaves'], 'Low-carb meal option.'),
('Veggie Burger', 'dinner', 400, '20 min', ARRAY['Beans', 'Oats'], ARRAY['Form patties', 'Grill'], 'Plant-based protein meal.'),
('Fruit Popsicles', 'desserts', 100, '5 min', ARRAY['Berries', 'Yogurt'], ARRAY['Freeze in molds'], 'Healthy frozen treat.'),
('Greek Yogurt Dip', 'snacks', 200, '5 min', ARRAY['Greek Yogurt', 'Herbs'], ARRAY['Mix ingredients'], 'Protein-rich snack.'),
('Spinach and Cheese Omelette', 'breakfast', 350, '10 min', ARRAY['Eggs', 'Spinach', 'Cheese'], ARRAY['Cook filled omelette'], 'Nutritious breakfast meal.'),
('Chicken and Broccoli Stir-Fry', 'dinner', 400, '15 min', ARRAY['Chicken Breast', 'Broccoli'], ARRAY['Stir fry quickly'], 'Balanced meal.'),
('Mango Smoothie', 'breakfast', 280, '5 min', ARRAY['Mangoes', 'Yogurt'], ARRAY['Blend smooth'], 'Refreshing vitamin-rich drink.'),
('Oatmeal with Nuts', 'breakfast', 400, '10 min', ARRAY['Oats', 'Almonds', 'Milk'], ARRAY['Cook and top'], 'Fiber and protein-rich meal.'),
('Baked Veggie Chips', 'snacks', 150, '20 min', ARRAY['Kale', 'Olive Oil'], ARRAY['Bake thin slices'], 'Healthy snack alternative.'),
('Tuna Salad', 'lunch', 350, '10 min', ARRAY['Tuna', 'Greek Yogurt'], ARRAY['Mix ingredients'], 'Light protein dish.'),
('Lentil Soup', 'lunch', 300, '30 min', ARRAY['Lentils', 'Carrots'], ARRAY['Simmer until soft'], 'Filling and nutritious.'),
('Egg Sandwich', 'breakfast', 350, '10 min', ARRAY['Eggs', 'Brown Bread'], ARRAY['Fry egg', 'Assemble'], 'Simple protein meal.'),
('Mixed Fruit Bowl', 'desserts', 200, '5 min', ARRAY['Mixed Fruits'], ARRAY['Chop and mix'], 'Refreshing and healthy dessert.')
ON CONFLICT DO NOTHING;

