-- Seed exercises data (copy from ExerciseScreen hardcoded data)
-- Run this after creating tables

INSERT INTO exercises (name, category, estimated_calories, benefits, steps, instructions, reps, difficulty) VALUES
('Running', 'cardio', 300, 'Improves cardiovascular health, burns calories, strengthens legs, boosts mood through endorphins.', ARRAY['Warm up for 5 minutes', 'Start at a comfortable pace', 'Gradually increase speed', 'Cool down for 5 minutes'], 'Run at a steady pace, maintaining good form. Keep your arms at 90 degrees and land midfoot.', '20-30 minutes', 'Intermediate'),
('Jumping Jacks', 'cardio', 15, 'Full body workout, improves coordination, increases heart rate, burns calories efficiently.', ARRAY['Stand with feet together, arms at sides', 'Jump while spreading legs and raising arms overhead', 'Return to starting position', 'Repeat continuously'], 'Keep the movement fluid and maintain a steady rhythm. Land softly on your feet.', '3 sets of 20 reps', 'Beginner'),
('Burpees', 'cardio', 20, 'Full body conditioning, builds muscle, burns fat, improves cardiovascular endurance.', ARRAY['Start standing', 'Drop into a squat with hands on floor', 'Jump feet back to plank', 'Do a push-up', 'Jump feet forward', 'Jump up with arms overhead'], 'Maintain proper form throughout. Modify by stepping instead of jumping.', '3 sets of 10 reps', 'Advanced'),
('Push-Ups', 'strength', 10, 'Builds chest, shoulders, and triceps, strengthens core, improves posture.', ARRAY['Start in plank position', 'Lower body until chest nearly touches floor', 'Push back up to starting position', 'Keep core tight throughout'], 'Keep your body in a straight line. Don''t let hips sag or pike up.', '3 sets of 15 reps', 'Intermediate'),
('Squats', 'strength', 12, 'Strengthens legs and glutes, improves balance, increases mobility, burns calories.', ARRAY['Stand with feet shoulder-width apart', 'Push hips back and bend knees', 'Lower until thighs are parallel to floor', 'Push through heels to stand'], 'Keep your chest up and knees tracking over toes. Don''t let knees cave inward.', '3 sets of 20 reps', 'Beginner'),
('Plank', 'strength', 5, 'Strengthens core, improves posture, builds stability, reduces back pain.', ARRAY['Start in forearm plank position', 'Keep body in straight line from head to heels', 'Engage core and hold', 'Don''t let hips drop or rise'], 'Draw your belly button toward your spine. Breathe steadily throughout.', '3 sets of 30-60 seconds', 'Intermediate'),
('Yoga Sun Salutation', 'flexibility', 50, 'Increases flexibility, builds strength, calms mind, improves circulation.', ARRAY['Start in mountain pose', 'Raise arms overhead', 'Fold forward', 'Half lift with flat back', 'Plank', 'Chaturanga', 'Upward dog', 'Downward dog', 'Step forward and fold', 'Rise up'], 'Flow through each pose with your breath. Move slowly and mindfully.', '5-10 rounds', 'Intermediate'),
('Hamstring Stretch', 'flexibility', 2, 'Lengthens hamstrings, reduces lower back tension, improves flexibility.', ARRAY['Sit with one leg extended', 'Bend other leg with foot against inner thigh', 'Reach toward extended foot', 'Hold and breathe', 'Switch sides'], 'Keep your back straight and hinge from the hips. Don''t bounce.', '30 seconds per side', 'Beginner'),
('Tree Pose', 'balance', 3, 'Improves balance, strengthens legs, increases focus, builds stability.', ARRAY['Stand on one leg', 'Place other foot on inner thigh or calf', 'Bring hands to prayer position', 'Focus on a fixed point', 'Hold and breathe', 'Switch sides'], 'Avoid placing foot on knee. Engage your core and stand tall.', '30-60 seconds per side', 'Intermediate'),
('Wall Sit', 'balance', 8, 'Strengthens legs, builds endurance, improves posture.', ARRAY['Stand with back against wall', 'Slide down until thighs are parallel to floor', 'Keep knees at 90 degrees', 'Hold position', 'Slide back up'], 'Keep your back flat against the wall. Don''t let knees go past toes.', '3 sets of 30-60 seconds', 'Intermediate')
-- Add more from hardcoded data as needed...
ON CONFLICT (id) DO NOTHING;
-- Note: Truncated for brevity. Full seed would include all ~50 exercises.

